# yaml 설정파일
# 계층 구조로 설정하기
# 공통된 property 항목은 맨 앞줄부터 사용하고
# : 을 붙여준 후
# 이후의 속성들은 tab 을 이용하여 들여쓰기 한 후 속성들을 설정

spring:
  devtools:
    restart.enabled: true
    remote.restart.enabled: true

  # 외부에서 접근하는 경로
  mvc:
    static-path-pattern: /static/**
  
  # 서버의 폴더 개방하기
  web:
    resources:
      static-locations: classpath:static/


  # DBMS Setting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootDB
    username: dosunggil
    password: '!Korea8080'



# ddl-auto ? update ??
# ??? ??? ???? ??? Alter table ? ???? ??? ??? ????.
# ????? update ? ??? ??? ?????.
# ??? update ? ???? ???? ??????
# ?? ??? VO ??? ??? ? ? ???? ??? ????? ??
# ??? Column ? ??? ?? ???(???) ???? ??? ??????.
# ??? ??? ?? dao.save() method ?? ??? ????.
# ?? VO ???? ?? ??? ??? ???? ???
# ???? ?? ??? ?? ??.
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true


  thymeleaf:
    prefix: classpath:html/
    suffix: .html
    mode: HTML5
    template-resolver-order: 0

# logback setup
logging:
  config: classpath:logback-local.xml
  level:
    com.cho.book: debug
    org.springframework: debug

